apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
stringData:
  MONGO_URL: "mongodb+srv://pkansif39:ansifpk123@eduhub.y1e7f.mongodb.net/auth?retryWrites=true&w=majority&appName=EduHub"
  PORT: "3000"
  KAFKA_BROKER: "kafka-srv:9092"
  JWT_ACCESSKEY: "itsjwtaccesskey"
  JWT_REFRESHKEY: "itsjwtRefreshkey"
  JWT_VERIFICATIONKEY: "itsjwtverificationkey"
  JWT_FORGOTPASSWORDEY: "itsjwtForgetkey"
  EMAIL: "pkansif39@gmail.com"
  PASSWORD: "tvtq zgcc skhn rliu"
  DOMAIN: "api.eduhublearning.online"
  ORGINS: '["http://client-srv:5173","http://localhost:5173","https://www.eduhublearning.online","https://api.eduhublearning.online","https://eduhub-s2po.vercel.app"]'
  SOCKET_PATH: "/auth/socket.io"
