name: Add test for Purchase Service 
on:
  pull_request:
    paths:
      - "purchase/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd purchase && npm install && npm run test:ci
