name: Add test for Message Service 
on:
  pull_request:
    paths:
      - "message/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd message && npm install && npm run test:ci
