name: Add test for courses Service 
on:
  pull_request:
    paths:
      - "courses/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd courses && npm install && npm run test:ci
